### ISSUE TITLE
Why Lens.into does nothing inside the map ?

### ISSUE THREAD

**Issue by lkuty** [obrok/lens#13]
Hello,
Thanks for this fantastic library which is very useful. I stumbled upon a weird behaviour of `Lens.into` when used inside a map, not a the top level. IMHO I think `test4_ko/1` should return a map instead of a list thanks to `Lens.into` in the expression:

```
Lens.map_values |> Lens.all |> Lens.into(%{}) |> Lens.map(h, fn {k,v} -> {k,v} end)
```

The code is copied below.

```
iex(1)> h = LensTest.get_a_map
%{
  "top" => %{
    "257" => %{
      "datetime" => "2020-03-03T14:58:30.200896+01:00",
      "value" => false
    }
  }
}
iex(2)> LensTest.test1_ok(h)
[
  {"top",
   %{
     "257" => %{
       "datetime" => "2020-03-03T14:58:30.200896+01:00",
       "value" => false
     }
   }}
]
iex(3)> LensTest.test2_ok(h)
%{
  "top" => %{
    "257" => %{
      "datetime" => "2020-03-03T14:58:30.200896+01:00",
      "value" => false
    }
  }
}
iex(4)> LensTest.test3_ok(h)
%{
  "top" => [
    {"257",
     %{"datetime" => "2020-03-03T14:58:30.200896+01:00", "value" => false}}
  ]
}
iex(5)> LensTest.test4_ko(h)
%{
  "top" => [
    {"257",
     %{"datetime" => "2020-03-03T14:58:30.200896+01:00", "value" => false}}
  ]
}
```

```elixir
defmodule LensTest do
  def get_a_map do
    %{"top" => %{"257" => %{"datetime" => "2020-03-03T14:58:30.200896+01:00", "value" => false}}}
  end

  def test1_ok(h) do
    Lens.all |> Lens.map(h, fn {k,v} -> {k,v} end)
  end

  def test2_ok(h) do
    Lens.all |> Lens.into(%{}) |> Lens.map(h, fn {k,v} -> {k,v} end)
  end

  def test3_ok(h) do
    Lens.map_values |> Lens.all |> Lens.map(h, fn {k,v} -> {k,v} end)
  end

  def test4_ko(h) do
    Lens.map_values |> Lens.all |> Lens.into(%{}) |> Lens.map(h, fn {k,v} -> {k,v} end)
  end

end
```

**Comment by obrok** [comment]
Thanks for reporting this and the other issue. I should be able to look into them this weekend.

**Comment by obrok** [comment]
OK, I think I figured this out (took me a while to remind myself of the more arcane stuff). Basically, you shouldn't think of `Lens.into` like just any other lens that you pipe into. Instead, it's a modifier that takes a lens and returns another lens. In particular, when you do:

```elixir
Lens.all() |> Lens.all()
```

That gets converted to:

```elixir
Lens.seq(Lens.all(), Lens.all())
``` 

The `|>` is just syntax sugar for convenience. But when you do:

```elixir
Lens.all() |> Lens.all() |> Lens.into(%{})
```

That is the same as regular `|>`, so it ends up as:

```elixir
Lens.into(Lens.all() |> Lens.all())
```

Just like any:

```elixir
a() |> b() |> c()
```

is the same as:

```elixir
c(a() |> b())
```

I admit this might be a bit counter-intuitive. I'll think if there might be a better API, or perhaps just putting the function in a different module like `Lens.Modifier.into()` might make it clearer?

In any case, the solution is to wrap the exact lens that you want to `into` into an `into`. So in your case:

```elixir
Lens.map_values() |> Lens.into(Lens.all())
```

If that's unclear, you can also take a look at this example I cooked up based on your problem:

```elixir
data = %{"top" => %{"key1" => %{"key2" => :value}}}

Lens.map_values()
|> Lens.into(Lens.all(), %{})
|> Lens.map(data, fn {x, y} -> {y, x} end)
|> IO.inspect()
# => %{"top" => %{%{"key2" => :value} => "key1"}}
```
