### ISSUE TITLE
How to handle a focus that isn't in the structure?

### ISSUE THREAD

**Issue by boxxxie** [obrok/lens#6]
just ran into an issue where i have a focus on something that may not exist, how should i handle this?

**Comment by boxxxie** [comment]
`Lens.satisfy(&(&1))` is what i used
this may be worthy of adding to the library as an idiom
or do you know of a different way to do this that is better/idiomatic?

**Comment by obrok** [comment]
Not quite sure what you mean - could you post an example?

**Comment by obrok** [comment]
Do you mean you want something like:

```elixir
iex> Lens.to_list(lens, %{a: 1})
[1]
iex> Lens.to_list(lens, %{})
[]
```

**Comment by boxxxie** [comment]
yeah, so i had a parent node that is sometimes nil, and i focus on it's children.
so similar to what you posted

**Comment by boxxxie** [comment]
example
:secondary is sometime nil
```
    people_lens =
      Lens.multiple([
        Lens.key(:primary),
        Lens.key(:secondary)])
      |> Lens.satisfy(exists) #existence check

    age_lens =
      people_lens
      |> Lens.both(Lens.key(:children) |> Lens.all)
      |> Lens.key(:age)
```

**Comment by obrok** [comment]
Yeah, I think `Lens.satisfy(&(&1))` is fine for this case... Not sure if there should be a separate function for this if such an easy solution exists.

**Comment by boxxxie** [comment]
I think it may not be obvious. 
may need more examples of how to use the library.

**Comment by obrok** [comment]
If you think you have a way to make this obvious in the API, please make a PR, closing for now.
